#define FLOW_TAP_TERM 150
#undef TAPPING_TERM
#define TAPPING_TERM 150

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "Dq6aK/5WyKK6"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

